### PR TITLE
Typescript

### PR DESCRIPTION
**Pull request by HorstFrank**
- https://nextjs.org/learn/excel/typescript/create-tsconfig
  - `echo '' > tsconfig.json`
    - https://www.typescriptlang.org/docs/handbook/compiler-options.html
  - `npm install --save-dev typescript @types/react @types/node`
  - `echo '' > next-env.d.ts`
  - update some files suffixes:
    - `mv components/date.js components/date.tsx`
    - `mv components/layout.js components/layout.tsx`
    - `mv lib/posts.js lib/posts.tsx`
    - `mv pages/posts/[id].js pages/posts/[id].tsx`
    - `mv pages/index.js pages/index.tsx`
    - `mv pages/_app.js pages/_app.tsx`
    - `mv pages/api/hello.js pages/api/hello.ts`
- https://nextjs.org/docs/basic-features/typescript
  - `npm run dev`

### CODE REVIEW

**Review by m-wiemers — APPROVED** [review]
Wow. An honor to see this ☀🌻

**Review by mrana17 — APPROVED** [review]
gj 👍

**Comment by DNaunin** [comment]
Very detailed description! Good Job! 🚀

**Review by SilviaBarcellini — APPROVED** [review]
Awesome! 👍

**Review by cboenke — APPROVED** [review]
lgtm 🚀

**Pull request merged**
